In [2]:
import numpy as np

def extract_matrices(data):
    A = data[:, :-1]
    C = data[:, -1]
    return A, C

def calculate_dimensionality(A):
    return A.shape[1]

def calculate_num_vectors(A):
    return A.shape[0]

def calculate_rank(A):
    return np.linalg.matrix_rank(A)

def calculate_pseudoinverse(A):
    return np.linalg.pinv(A)

def main():
    # Define the data
    data = np.array([
        [20, 6, 2, 386],
        [16, 3, 6, 289],
        [27, 6, 2, 393],
        [19, 1, 2, 110],
        [24, 4, 2, 280],
        [22, 1, 5, 167],
        [15, 4, 2, 271],
        [18, 4, 2, 274],
        [21, 1, 4, 148],
        [16, 2, 4, 198]
    ])

    # Extract matrices A and C
    A, C = extract_matrices(data)

    # Print matrices A and C
    print("Matrix A (features details):\n", A)
    print("Matrix C (payment details):\n", C)

    # Calculate and print dimensionality of the vector space
    dimensionality = calculate_dimensionality(A)
    print("\nThe dimensionality of the vector space is:", dimensionality)

    # Calculate and print the number of vectors in the vector space
    num_vectors = calculate_num_vectors(A)
    print("The number of vectors in this vector space is:", num_vectors)

    # Calculate and print the rank of matrix A
    rank_A = calculate_rank(A)
    print("The rank of matrix A is:", rank_A)

    # Calculate and print the pseudo-inverse of matrix A
    pseudoinv_A = calculate_pseudoinverse(A)
    print("\nThe pseudo-inverse of matrix A is:\n", pseudoinv_A)

if __name__ == "__main__":
    main()


Matrix A (features details):
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
Matrix C (payment details):
 [386 289 393 110 280 167 271 274 148 198]

The dimensionality of the vector space is: 3
The number of vectors in this vector space is: 10
The rank of matrix A is: 3

The pseudo-inverse of matrix A is:
 [[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]


In [3]:
import numpy as np

def calculate_predictions(pseudoinv_A, C):
    return np.dot(pseudoinv_A, C)

def calculate_product_costs(A, predictions):
    return np.dot(A, predictions)

def main():
    # Define the data
    data = np.array([
        [20, 6, 2, 386],
        [16, 3, 6, 289],
        [27, 6, 2, 393],
        [19, 1, 2, 110],
        [24, 4, 2, 280],
        [22, 1, 5, 167],
        [15, 4, 2, 271],
        [18, 4, 2, 274],
        [21, 1, 4, 148],
        [16, 2, 4, 198]
    ])

    # Extract matrices A and C
    A = data[:, :-1]
    C = data[:, -1]

    # Calculate the pseudo-inverse of matrix A
    pseudoinv_A = np.linalg.pinv(A)

    # Calculate the model vector 'predictions' for estimating the product costs
    predictions = calculate_predictions(pseudoinv_A, C)
    print("\nThe model vector 'predictions' for estimating the product costs:", predictions)

    # Compute the estimated cost of each product
    product_costs_estimated = calculate_product_costs(A, predictions)

    print("\nThe estimated cost of each product is as follows:")
    for i, cost in enumerate(product_costs_estimated):
        print(f"The estimated cost of Product {i+1} is: Rs.{cost:.2f}")

if __name__ == "__main__":
    main()



The model vector 'predictions' for estimating the product costs: [ 1. 55. 18.]

The estimated cost of each product is as follows:
The estimated cost of Product 1 is: Rs.386.00
The estimated cost of Product 2 is: Rs.289.00
The estimated cost of Product 3 is: Rs.393.00
The estimated cost of Product 4 is: Rs.110.00
The estimated cost of Product 5 is: Rs.280.00
The estimated cost of Product 6 is: Rs.167.00
The estimated cost of Product 7 is: Rs.271.00
The estimated cost of Product 8 is: Rs.274.00
The estimated cost of Product 9 is: Rs.148.00
The estimated cost of Product 10 is: Rs.198.00


In [4]:
import numpy as np

def load_data():
    # Loading all the data from the excel
    purchase_data = np.array([
        [20, 6, 2, 386],
        [16, 3, 6, 289],
        [27, 6, 2, 393],
        [19, 1, 2, 110],
        [24, 4, 2, 280],
        [22, 1, 5, 167],
        [15, 4, 2, 271],
        [18, 4, 2, 274],
        [21, 1, 4, 148],
        [16, 2, 4, 198]
    ])

    # Create the binary data based on payment made
    y_train = np.where(purchase_data[:, -1] > 200, 1, 0)
    X_train = purchase_data[:, :-1]

    return X_train, y_train

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

def knn_predict(X_train, y_train, x_test, k=3):
    distances = []
    for i, x_train in enumerate(X_train):
        distance = euclidean_distance(x_train, x_test)
        distances.append((distance, y_train[i]))
    distances = sorted(distances)[:k]
    counts = np.bincount([d[1] for d in distances])
    return np.argmax(counts)

def main():
    # Load the data
    X_train, y_train = load_data()

    # Predict the class for each customer payment
    print("Predicted Classes:")
    for i, customer in enumerate(X_train):
        predicted_class = knn_predict(X_train, y_train, customer)
        if predicted_class == 1:
            print(f"Customer {i+1} is: RICH")
        else:
            print(f"Customer {i+1} is: POOR")

if __name__ == "__main__":
    main()


Predicted Classes:
Customer 1 is: RICH
Customer 2 is: RICH
Customer 3 is: RICH
Customer 4 is: POOR
Customer 5 is: RICH
Customer 6 is: POOR
Customer 7 is: RICH
Customer 8 is: RICH
Customer 9 is: POOR
Customer 10 is: RICH


In [6]:
import pandas as pd
import statistics
import matplotlib.pyplot as plt

# Load data from Excel file
file_path = "C:\\Users\\HP\\Downloads\\Lab Session1 Data.xlsx"
df_stock = pd.read_excel(file_path, sheet_name='IRCTC Stock Price')

# Task 1: Calculate mean and variance of Price data
price_mean = statistics.mean(df_stock['Price'])
price_variance = statistics.variance(df_stock['Price'])

print(f"Mean of Price: {price_mean}")
print(f"Variance of Price: {price_variance}")

# Task 2: Select price data for all Wednesdays and calculate sample mean
wednesday_prices = df_stock[df_stock['Day'] == 'Wed']
wednesday_prices=wednesday_prices['Price']
wednesday_mean = statistics.mean(wednesday_prices)

print(f"Sample Mean of Wednesday Prices: {wednesday_mean}")

# Task 3: Select price data for the month of Apr and calculate sample mean
april_prices = df_stock[df_stock['Month'] == 'Apr']
april_prices=april_prices['Price']
april_mean = statistics.mean(april_prices)

print(f"Sample Mean of April Prices: {april_mean}")

# Task 4: Probability of making a loss over the stock
loss_probability = len(df_stock[df_stock['Chg%'] < 0]) / len(df_stock)
print(f"Probability of making a loss: {loss_probability}")

# Task 5: Probability of making a profit on Wednesday
wednesday_profit_probability = len(wednesday_prices[wednesday_prices.diff() > 0]) / len(wednesday_prices)
print(f"Probability of making a profit on Wednesday: {wednesday_profit_probability}")

# Task 6: Conditional probability of making profit given today is Wednesday
conditional_profit_given_wednesday = wednesday_profit_probability / len(df_stock[df_stock['Day'] == 'Wed'])
print(f"Conditional Probability of making profit given today is Wednesday: {conditional_profit_given_wednesday}")

# Task 7: Scatter plot of Chg% data against the day of the week
plt.scatter(df_stock['Day'], df_stock['Chg%'])
plt.xlabel('Day of the Week')
plt.ylabel('Chg%')
plt.title('Scatter Plot of Chg% against Day of the Week')
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HP\\Downloads\\Lab Session1 Data.xlsx'